### ISSUE TITLE
Use an exact position for annotation 

### ISSUE THREAD

**Issue by azaa21** [eweitz/ideogram#107]
Greetings,

I want to ask about the possibility of using the exact position for annotation? because when I try to use it as it is without scaling as in [1], some positions are not presented and the whole annotation disappears.
Any idea how I can do that?

Example of positions that not fit with the chrs positions:
In chr9
{
            "chr": "9",
            "annots": [
                [
                    "",
                    79318384,
                    0,
                    0,
                    50.0
                ],
                [
                    "",
                    139911697,
                    0,
                    0,
                    38.0
                ],
                [
                    "",
                    139911697,
                    0,
                    0,
                    62.0
                ],
                [
                    "",
                    86474241,
                    0,
                    0,
                    56.0
                ],
                [
                    "",
                    27359226,
                    0,
                    0,
                    42.0
                ],
                [
                    "",
                    79318384,
                    0,
                    0,
                    50.0
                ],
                [
                    "",
                    27359226,
                    0,
                    0,
                    58.0
                ]
            ]
        },

[1] https://github.com/eweitz/ideogram/blob/master/scripts/python/create_annots.py#L131

**Comment by azaa21** [comment]
Sorry this is different example and yes it works also with me.
Could you please try this example:
https://raw.githubusercontent.com/azaa21/ideogramTest/master/positions.json

I think the problem is with Chr9 positions, because once I replace it with the ones that in example pos.json it works well.

**Comment by eweitz** [comment]
@azaa21, I get this error with your [positions.json](https://raw.githubusercontent.com/azaa21/ideogramTest/master/positions.json) file:

```
coordinate-converters.js:13 Uncaught Error: Base pair out of range.  bp: 139911697; length of chr9: 138394717
    at throwBpToPxError (coordinate-converters.js:13)
    at Ideogram.convertBpToPx (coordinate-converters.js:66)
    at addAnnotsForChr (process.js:150)
    at addAnnots (process.js:187)
    at Ideogram.processAnnotData (process.js:229)
    at processAnnots (finish-init.js:39)
    at finish-init.js:58
```

The message `Base pair out of range.  bp: 139911697; length of chr9: 138394717` reports that the genomic position of that annotation is out of range of chr9.

The cause of your issue is likely that Ideogram uses GRCh38 as the default genome assembly for human.  [Chromosome 9 in GRCh38](https://www.ncbi.nlm.nih.gov/nuccore/NC_000009.12) is 138,394,717 bp in length.  However, [chromosome 9 in GRCh37](https://www.ncbi.nlm.nih.gov/nuccore/NC_000009.11) is 141,213,431 bp.  

So I suspect your annotations in positions.json are on GRCh37, the previous major version of the human reference genome assembly.

Try adding `assembly: 'GRCh37'` to your Ideogram configuration, e.g.:

```
var config = {
  organism: 'human',
  assembly: 'GRCh37',
  annotationsPath: 'path/to/your/positions.json'
};
```

The API documentation for [`assembly`](https://github.com/eweitz/ideogram/blob/master/api.md#assembly) has more details.
