### ISSUE TITLE
Expression-level no-effect problem

### ISSUE THREAD

**Issue by FDUguchunhui** [eweitz/ideogram#148]
The data is like this. The column CFASN, Blood, and LTB4 is the gene expression under three different conditions.
![image](https://user-images.githubusercontent.com/17284220/58515141-eaacee00-8171-11e9-958a-d292646177db.png)

For each condition, JSON files were created as SRR562646.json for each condition except we don't have gene_type(use a constant instead).
![image](https://user-images.githubusercontent.com/17284220/58515208-22b43100-8172-11e9-8ef2-96bf0d3a8635.png)

However, Eric's package will give the same plot for all three conditions even if the expression-level are totally different. But they do share the same data format even though those genes have expression-level of 0.
![image](https://user-images.githubusercontent.com/17284220/58515101-d1a43d00-8171-11e9-80bf-cf259557b9c0.png)
![image](https://user-images.githubusercontent.com/17284220/58515104-d668f100-8171-11e9-83f4-f3e8d10f8b24.png).

I spent a lot of time to try to figure out what's wrong. When I deleted those genes have expression-level of 0. The plot changes.
![image](https://user-images.githubusercontent.com/17284220/58515448-d9181600-8172-11e9-8203-02fadc151ed1.png)

Then, I try to set expression-level as different constants, such as 5, 7, 100. I found the expression-level won't have an impact on the plot at all. There must be something wrong with the source code.
![image](https://user-images.githubusercontent.com/17284220/58515514-1d0b1b00-8173-11e9-832d-918df614406a.png)

**Comment by eweitz** [comment]
@FDUguchunhui, could you provide the following, to help me debug this issue?

* Your Ideogram configuration object, i.e. the "config" object you pass into `new Ideogram(config)`
* Your JSON file containing Ideogram annotations, likely referenced via the `annotationsPath` property in the above configuration object

**Comment by FDUguchunhui** [comment]
Hi Eric:
 
 
 
I’ve change the path of configuration file, shouldn’t be a problem for you.
 
 
 
The expression-level are base 10 log-transformed(you can find origin level at all.csv), most of them are 0 (but you can see delete them will change the plot).
 
 
 
In the CFASN.json, I deleted all the expression-level = 0 json object (originally, those three are the same).
 
 
 
I am not sure whether you can open the RAR file. If you have trouble open it, tell me then I can send separately.
 
 
 
Yours
 
 
 
Chunhui 





------------------ Original ------------------

**Comment by eweitz** [comment]
Could you attach the RAR file you mentioned?  You can do so by clicking the "Attach files..." bar immediately below the GitHub GUI's comment text input field.

**Comment by FDUguchunhui** [comment]
[file.zip](https://github.com/eweitz/ideogram/files/3237109/file.zip)

**Comment by eweitz** [comment]
Thanks for those examples files, Chunhui.

The three plots in your original comment look the same because they are unfiltered.  In other words, they look like https://eweitz.github.io/ideogram/annotations-histogram (with a smaller bar width) because, by default, the histogram annotation layout simply shows the distribution of annotations.  

In your case, like the linked example, your annotations represent human genes.  So the plot will show the distribution of all human genes, which is the same among your three ideograms.  That's expected behavior.

You want to see differences by expression among the three annotation datasets.  To do that, you need to apply filters, specifically the "Expression level" filter as in https://eweitz.github.io/ideogram/annotations-histogram.  The easiest way to apply filters is by clicking on them in the UI; you could also set them programmatically in the UI, or (less flexibly) upstream in your code to generate Ideogram annontations.

Your Ideogram annotation JSON files use floats (e.g. 5.61350494110629) for expression values.  The filters require integers (e.g. 5), like [SRR562646.json](https://raw.githubusercontent.com/eweitz/ideogram/74142c9a48536caecaf3b0f7a9e60b8439007973/dist/data/annotations/SRR562646.json).  If you round your expression values, that should work.

For any further investigation on this, let's use your repo at https://github.com/FDUguchunhui/ideogram as our workspace for debugging code.  (An archive file like your .zip is helpful; a repo is even better.)

Let me know if this resolves your issue!

**Comment by FDUguchunhui** [comment]
Thank you, Eric. It solves the problem. But still, I doubt the meaning of plot the distribution of the whole annotations. I think when you haven't check any box, the effect should equal to you check all the box. Or the default is all the box are checked. 
Another question, the requirement that I have to use an integer as expression-level is kind questionable because it could lead to two similar expressions e.g. 4.49 and 4.5 round to 4 and 5, but in log10 level, the difference is 10 fold. 
I've tried doing not use the log10 transformation but it seems that the integer level of 1-7 limited all the expressions greater than 7. Do you have a plan to add this feature in the future?
Again, thank you for your time.

**Comment by eweitz** [comment]
Chunhui, that's worthwhile feedback.

> I think when you haven't check any box, the effect should equal to you check all the box. 

Agreed.  That is the case in https://eweitz.github.io/ideogram/annotations-histogram.  Is it not the case with your plots?

> ...the requirement that I have to use an integer as expression-level is kind questionable because it could lead to two similar expressions e.g. 4.49 and 4.5 round to 4 and 5, but in log10 level, the difference is 10 fold.
>
> I've tried doing not use the log10 transformation but it seems that the integer level of 1-7 limited all the expressions greater than 7. Do you have a plan to add this feature in the future?

Apologies, my prior suggestion for rounding could have been refined.  

The integers 1-7 required for the "Expression level" filter in https://eweitz.github.io/ideogram/annotations-histogram are merely placeholders for whatever expression level you consider to be "low", "medium", "high", etc.  They have no inherent meaning.  It's up to you to decide how your underlying expression values map to those summary levels.

You could simply round the floats for your log10-transformed expression values to meet that requirement.  You're right to note that caveat, but fundamentally you would need to summarize, and summarization entails less precision.  

Here's how FlyBase maps expression levels to underlying expression values as measured in RPKM units:
<img width="766" alt="flybase_expression_level_map_to_rpkm" src="https://user-images.githubusercontent.com/1334561/58748267-fe8f7300-8443-11e9-9010-e1fdaf9397bd.png">
https://flybase.org/rnaseq/profile_search

I don't actually know many details of your data -- e.g. whether the underlying units of expression are RPKM, TPM or something else.  So I'm not the best person to say what is "high" or "low" expression in your data.  The integers required for "Expression level" enable you to define that.

I hope this helps!
