### ISSUE TITLE
Briefly Document chromosome biology / colors? 

### ISSUE THREAD

**Issue by zfrenchee** [eweitz/ideogram#156]
This tool is much appreciated. I'm curious what each of the colors represents. 
<img width="1356" alt="Screen Shot 2019-06-27 at 1 02 24 PM" src="https://user-images.githubusercontent.com/2761597/60285676-17bcff80-98dc-11e9-8650-b474f30f0cfd.png">

What is the blue cross-hatching? Why are some centromeres longer than others? A link to somewhere which answers these questions would be much appreciated. Going through the data folder in this directory didn't yield any obvious answers. 

Thanks!

**Comment by eweitz** [comment]
Greetings, Alexander!  Here you go.

# Chromosome biology in Ideogram.js
<img width="1166" alt="chromosome_biology_telomere_centromere_ideogram_2018-10-24" src="https://user-images.githubusercontent.com/1334561/60329274-09afc300-995e-11e9-8c24-a195c8c05d87.png">
<img width="1167" alt="chromosome_biology_p_arm_q_arm_ideogram_2018-10-24" src="https://user-images.githubusercontent.com/1334561/60329273-09afc300-995e-11e9-8c1a-c2f3f19f8877.png">
<img width="1169" alt="chromosome_biology_light_dark_bands_pink_centromere_cross_hatching_variable_regions_2018-10-24" src="https://user-images.githubusercontent.com/1334561/60329272-09afc300-995e-11e9-982c-639dde75afb6.png">

These informational graphics and other higher-level documentation can be found in [slides for a 2018 presentation on Ideogram.js](https://speakerdeck.com/eweitz/ideogramjs-chromosome-visualization-with-javascript) delivered at the Broad Institute of MIT and Harvard.  I just linked them from this repo's [README](https://github.com/eweitz/ideogram) as well.

Now, on to your specific questions.

# What is the blue cross-hatching?

Variable regions and stalks.  They are an intriguing part of the human genome.

Variable regions are seen cytogenetically in "1q12, 3q11.2, 9q12, 16q11.2, 19p12, 12q12, Yq12, and the short arms of all acrocentric chromosomes"\[1] -- i.e. chromosomes 13, 14, 15, 21, and 22.  Notably, "the representations of these variable regions are not based on measurements"[1].

Stalks are secondary constrictions in [satellite chromosomes](https://en.wikipedia.org/wiki/Satellite_chromosome).  Secondary constrictions are spans of very condensed chromatin that appear thread-like under a microscope during metaphase.  (Centromeres are the primary constriction.)  Stalks appear on chromosomes 13, 14, 15, 21, and 22.  The p-terminal regions of those acrocentric chromosomes are called "satellite chromosomes" because they appear almost detached from the main chromosome body.

Stalks are not well depicted in Ideogram.js.  Refining them has been in my mental backlog.

These cytogenetic terms and their graphical rendering in Ideogram.js descend from "[ISCN: An Internal System for Human Cytogenomic Nomenclature (2016)](https://www.amazon.com/ISCN-2016-International-Cytogenomic-Nomenclature/dp/3318058572)" by way of the Ideogram, [Genome Decoration Page](https://www.ncbi.nlm.nih.gov/genome/tools/gdp), and [cytogenetic banding data](https://ftp.ncbi.nlm.nih.gov/pub/gdp/) from NCBI.

You might also be interested in [how Ideogram's chromosome data is generated](https://github.com/eweitz/ideogram/issues/72).

\[1] [ISCN 2016](https://www.amazon.com/ISCN-2016-International-Cytogenomic-Nomenclature/dp/3318058572), pages 13-14

# Why are some centromeres longer than others?

Because NCBI represents them as such.

Specifically, the ISCN coordinate length (`iscn_stop` - `iscn_start`) in https://ftp.ncbi.nlm.nih.gov/pub/gdp/ideogram_9606_GCF_000001305.15_850_V1 differs among centromeres, i.e. the `acen` bands between the p- and q-arms.  For example, the chr1 centromere has ISCN length 460 (= 7579 - 7119), whereas chr6 centromere has ISCN length 237 (3658 - 3421).  So, per that data, the centromeres on chr6 and chr1 are about 50% different in length.

Visually inspecting their depiction in Ideogram.js, you can see the concordance with NCBI data.

The ISCN coordinates are not exact.  They were derived, as I vaguely recall from accounts, from a combination of A) FISH-mapped clones from Terry Furey at UCSC [2] and B) physical ruler measurements of magnified ideogram graphics from the ISCN reference manual cited earlier.

Although inexact, it is very useful to have reference chromosome banding data.  NCBI is a good source for it.

\[2] "[Tracks Based on Genome-Wide Maps](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC186604/#__sec8)" in The Human Genome Browser at UCSC, Kent et al. (2002) seems to be the best reference.

**Comment by zfrenchee** [comment]
Thanks!
