### ISSUE TITLE
Yeast example does not work

### ISSUE THREAD

**Issue by vsoch** [eweitz/ideogram#223]
Heyo! It looks like there is a missing / mislabeled static file preventing the yeast example from working:

![image](https://user-images.githubusercontent.com/814322/91896373-fa10c600-ec55-11ea-833b-6bdce521e294.png)

**Comment by vsoch** [comment]
Here is the link! https://eweitz.github.io/ideogram/eukaryotes?org=saccharomyces-cerevisiae

**Comment by eweitz** [comment]
Thanks for reporting the bug, @vsoch.  This was caused by a silently backwards-incompatible upstream API change.  I'll likely deploy a fix within a few days.

**Comment by eweitz** [comment]
[Fixed](https://eweitz.github.io/ideogram/eukaryotes?org=saccharomyces-cerevisiae)!  Thanks again.  Technical details are in #225.

**Comment by vsoch** [comment]
Thank you @eweitz ! One more quick (probably naive) question - is there any reason that I can't see detail in the genome beyond a gray bar? For example here is yeast:

![image](https://user-images.githubusercontent.com/814322/92309364-208a7600-ef62-11ea-9dec-cd224b8b03cc.png)

and here are some others with details:

![image](https://user-images.githubusercontent.com/814322/92309375-3c8e1780-ef62-11ea-83c8-83241db13acb.png)

You have a lot of really beautiful visualizations here https://eweitz.github.io/ideogram/ - is there one that would do well to visualize and allow someone to dig in to the yeast genome? E.g., we're working on a site that has gene-level information, and it would be cool to have a diagram to explore, find a gene, and then click to get there.

**Comment by eweitz** [comment]
Hi @vsoch, you asked:

> is there any reason that I can't see detail in the genome beyond a gray bar?

Yes, that's due to lack of cytogenetic banding data.  

Such bands are available for a few organisms (e.g. rat), but not readily for yeast.  Most band data is from NCBI, and I occasionally forage band data from other resources when someone inquires.  There is also a level between the "fully banded" view like your rat example and the grey bar like yeast.  The intermediate level adds centromeres -- the most important feature of a chromosome after its length.  For more on bands, centromeres, and chromosome data in Ideogram, check out [slides 6-9 here](https://speakerdeck.com/eweitz/designing-genome-visualizations-with-ideogramjs?slide=6) and [slide 21 here](https://speakerdeck.com/eweitz/ideogramjs-chromosome-visualization-with-javascript?slide=21).

I just found _Saccharomyces cerevisiae_ centromere data to enrich the yeast ideogram.  I'll add that soon and let you know.

> is there one that would do well to visualize and allow someone to dig in to the yeast genome? E.g., we're working on a site that has gene-level information, and it would be cool to have a diagram to explore, find a gene, and then click to get there

Not yet.  I'll look into adding yeast to [Ideogram for related genes](https://eweitz.github.io/ideogram/related-genes).  That example lets the user search for a gene, and plots its position and the position of paralogs (sequentially similar genes in the same organism) and interacting genes (genes immediately up- or down-stream in a biochemical pathway).

Beyond that, something like [Annotations, basic](https://eweitz.github.io/ideogram/annotations-basic) gives the gist for how to plot a gene in Ideogram.

Your site sounds interesting, and useful!  Could you let me know when it's ready?

**Comment by vsoch** [comment]
> I just found Saccharomyces cerevisiae centromere data to enrich the yeast ideogram. I'll add that soon and let you know.

Wow thank you! Please let me know if I can help! I've looked at the source code for the examples that I linked, and it looks like they both generate a config object to then interact with the ideogram.js module. I was thinking if I could generate [this data file](https://raw.githubusercontent.com/eweitz/ideogram/gh-pages/data/annotations/SRR562646.json) for yeast it would be possible to get a similar interactive genome. So - I'm here to help if there is something that I can do! I'm so appreciative for your help!

> Your site sounds interesting, and useful! Could you let me know when it's ready?

Of course! I definitely hope we finish up in the next few months.

**Comment by eweitz** [comment]
Hi @vsoch, Ideogram now shows [centromeres for yeast](#229)!  I'll release that this weekend and update here.

Also, you wrote:

> if I could generate [this data file](https://raw.githubusercontent.com/eweitz/ideogram/gh-pages/data/annotations/SRR562646.json) for yeast it would be possible to get a similar interactive genome.

True.  The hard part is getting such a data file.  That [SRR562646.json](https://raw.githubusercontent.com/eweitz/ideogram/gh-pages/data/annotations/SRR562646.json) gene expression file you note was generated by the [rnaseqview pipeline](https://github.com/NCBI-Hackathons/rnaseqview#rnaseqview).  The pipeline code is free, open, and documented, but generally not maintained or actively supported.

An easier approach would be to start with a genes file, and omit expression data.  The basic feature data (names, positions, and types for a list of genes) is easier to find, more universal, and simpler -- and still somewhat interesting.  The visualization would look like [Annotations, histogram](https://eweitz.github.io/ideogram/annotations-histogram), but for yeast and lacking an "Expression level" facet.

Does that seem promising?  If so, I have some code that could be useful.

**Comment by vsoch** [comment]
> Does that seem promising? If so, I have some code that could be useful.

Yes! My naive sense would be to start with systematic names, and then use the SGD database API to get the names, positions, and types - the expression would vary based on the dataset. If you have something to start in that direction, I could definitely give it a shot!

**Comment by eweitz** [comment]
> I'll release that this weekend and update here.

This is live: http://localhost/ideogram/eukaryotes?org=saccharomyces-cerevisiae.

> My naive sense would be to start with systematic names, and then use the SGD database API to get the names, positions, and types - the expression would vary based on the dataset.

That approach makes sense!  I'll link to the relevant code I mentioned soon.
