### ISSUE TITLE
Annotating MT Chromosome

### ISSUE THREAD

**Issue by chriscdm** [eweitz/ideogram#224]
Hello, thank you for this handy tool! 

I am trying to use this to add a simple ideogram to a rare genetic disease portal, I am showing an ideogram with one chromosome highlighted at a time and one gene annotated. The user will be able to select genes associated with the genetic disease to see where it is located.

(Please forgive my ignorance regarding genetics in relation to my issue). Several of the genes I am trying to annotate are listed as MT. [Here is an example of one.](https://www.ncbi.nlm.nih.gov/genome/gdv/browser/gene/?id=4512) I have attempted to get MT to show up on the ideogram using `showNonNuclearChromosomes: true` but I cannot get it to display.

Is there another way to show MT for a human ideogram? Is annotating an MT gene not something that would be appropriate?

Thank you!

**Comment by eweitz** [comment]
Hi Chris, great questions.

> Is there another way to show MT for a human ideogram?

Not yet with this tool.  I wasn't sure it was worth the effort.  Given your message, I suspect it is.

> Is annotating an MT gene not something that would be appropriate?

It's reasonable to do, in my opinion.  Chromosome MT poses unique rendering challenges for chromosome visualization: 

1. MT is very small (sometimes vanishingly small) relative to the nuclear chromosomes.
2. MT is usually depicted as a circle rather than line.  

I'll show MT in human as already done for other organisms in Ideogram.js.  

In the whole-genome view, I suspect human chrMT itself will be invisible, because at scale it's less than a speck compared to the nuclear chromosomes (chr1 - chr22).  In other words, human MT will [display like MT in _C. elegans_](http://localhost:8080/examples/vanilla/eukaryotes?org=caenorhabditis-elegans) and [like NCBI Genome Data Viewer](https://www.ncbi.nlm.nih.gov/genome/gdv/browser/genome/?id=GCF_000001405.39).

In the single-chromosome view -- where we're not concerned with relative size -- Ideogram.js displays MT as a line.  This will also be similar to NCBI GDV, which, although it omits it from the single-chromosome ideogram view, includes a linearized chromosome in its Sequence Viewer.

Assuming this raises no red flags for you, I'll take on this enhancement and update you as I make progress.

**Comment by chriscdm** [comment]
thank you again for this, Eric! We really appreciate the enhancement! 

I will share once our tool goes live!

**Comment by eweitz** [comment]
This is live: http://localhost/ideogram/highlights-basic.
