### ISSUE TITLE
Software Showcase!

### ISSUE THREAD

**Issue by vsoch** [eweitz/ideogram#240]
Hey @eweitz! Sorry for two issues in one weekend, one day! This one is more fun :) I would like to share ideogram.js on the rseng software showcase this week https://rseng.github.io/rseng/blog/ and I'm wondering if there are any interesting stories, historical tidbits, or resources that you would like to add? The post serves as a general introduction to the software to get folks excited, and possibly find a tool they would find useful for their work. 

The post is currently in draft mode, you can see [here](https://github.com/rseng/rseng/blob/gh-pages/_posts/software/2020-10-04-ideogram.md) and the rendering of that is below!

![Screenshot_2020-10-04 Research Software - ideogram js](https://user-images.githubusercontent.com/814322/95025315-023d9600-0646-11eb-8a22-e9c178dd6bf4.png)

I usually release on lat Sunday, but I was a bit late today because I was having fun with #239, so we can definitely aim for early this week instead! Also, I wanted to ask if there is an associated paper or DOI that users of your software can cite? if you haven't ever done it before (and there is no paper) I highly recommend using zenodo -> https://zenodo.org/. It has a GitHub integration so it can be automated so that releases update the DOI.

**Comment by eweitz** [comment]
Hi @vsoch, thanks for featuring Ideogram :).  [The blog post](https://rseng.github.io/rseng/software/ideogram) looks good!

Small copyedit: the library name can be rendered as "Ideogram.js" or "Ideogram" -- always with capital "I".

Interesting tidbit: I began Ideogram.js [in February 2015](https://github.com/eweitz/ideogram/commit/b615e0f0a06fee451f07f5b8582eb772d1097f28), and have developed it as a personal side project on nights and weekends almost daily since.

Resources:
* [Ideogram.js: Chromosome visualization with JavaScript](https://speakerdeck.com/eweitz/ideogramjs-chromosome-visualization-with-javascript), October 2018
* [Designing genome visualizations with Ideogram.js](https://speakerdeck.com/eweitz/designing-genome-visualizations-with-ideogramjs), April 2020

Regarding citations, I've historically recommended:

Weitz, Eric M. Ideogram.js. 2015. https://github.com/eweitz/ideogram.

There's also a more traditional publication for a related work:

Weitz, Eric M.; Pantano, Lorena; Zhu, Jingzhi; Upton, Bennett; Busby, Ben. [Viewing RNA-seq data on the entire human genome](https://f1000research.com/articles/6-596/v1). F1000Research 2017, 6:596

The latter work has a DOI (see link), but I'll look into integrating Zenodo for DOIs for this repository itself.

**Comment by vsoch** [comment]
Thank you, I've made the fixes! https://github.com/rseng/rseng/commit/4c950a5dd08b5e7c360815c9c5af0ff4ad6c743f. +1 for integrating zenodo, it's really useful. I think we are good for this particular issue, so I'm going to close. Thanks again!
