### ISSUE TITLE
ideogRam R htmlwidget package

### ISSUE THREAD

**Issue by wangtulao** [eweitz/ideogram#78]
Hi Eric,

I have initialized an R htmlwidget package for ideogram. [https://github.com/wangtulao/ideogRam], and so far I'm able to reproduce some simple examples. 

But the main issue in the current R package is that, the R generated html file or js lib, cannot automatically find/load the "data/" folder, e.g. importing band, then, as a temp fix, I have to manually copy "data/" to the corresponding dataDir location (such as the ones in my example folder). For the same reason, the current R package cannot work in Shiny (since I cannot cp data/ folder to the shiny's runtime environment).

Another issue is due to my lack of JS knowledge, currently the onLoad or call back feature is not available yet. Maybe you can have some quick ideas or suggestions for the above issues.

Thanks!
Freeman

**Comment by eweitz** [comment]
Wow, Freeman!  [ideogRam](https://github.com/wangtulao/ideogRam) looks like a promising R wrapper for Ideogram.js.  @seandavi had suggested that I do something like this a while ago, but I have no experience with R.  I'm glad you've taken this on, @wangtulao!

> But the main issue in the current R package is that, the R generated html file or js lib, cannot automatically find/load the "data/" folder...

I suspect that issue is addressed by the newest version of Ideogram.js, [v0.9.0](https://github.com/eweitz/ideogram/releases/tag/v0.9.0), released yesterday.  Previously, one often had to specify a [`dataDir`](https://github.com/eweitz/ideogram/blob/master/api.md#datadir) property in the configuration object passed in to instantiate Ideogram.  Now, [`dataDir` is inferred](https://github.com/eweitz/ideogram/blob/4bd20d2b04b83647bd737f56c4cb39127e8bb5f0/src/js/core.js#L302) from the "src" attribute of the ideogram script loaded in the HTML document.

So I would first try simply updating the copy of Ideogram.js used by ideogRam.

> For the same reason, the current R package cannot work in Shiny (since I cannot cp data/ folder to the shiny's runtime environment).

Hmm.  Ideogram.js [depends on](https://github.com/eweitz/ideogram/blob/4bd20d2b04b83647bd737f56c4cb39127e8bb5f0/src/js/core.js#L2553) having access to the contents of the `data/` folder.  If it's impossible to send an HTTP request to `dataDir` on the user's Shiny runtime environment, try setting `dataDir` to a remote URL like so:
```
var ideogram = new Ideogram({
  organism: 'human',
  dataDir: 'https://unpkg.com/ideogram@0.9.0/dist/data/bands/native/'
});
```

I am not enamored with that workaround, as it requires an Internet connection, but perhaps it suffices for now.

**Comment by wangtulao** [comment]
Awesome, you are right! dataDir issue is fixed by using the latest Ideogram.js v0.9.0. Now my basic examples work in Shiny! Your update is just in time. =)

I have 2 questions:

1. Is there a quick way to pass/assign an id for Ideogram object, in this wrapper htmlwidget js [code] (https://github.com/wangtulao/ideogRam/blob/master/inst/htmlwidgets/ideogRam.js)? Since htmlwidgets will automatically generate it's own id, pass/link the ids will enable us to host multiple Ideogram viz on the same page. 

1. Is there a similar solution to dataDir for inputting `annotationsPath` arg? e.g. in my R [example 2](https://github.com/wangtulao/ideogRam/blob/master/create_htmlwidgets.R), I have to hard code annotationsPath as below. I think I could rebuild and move the saveWidget() part into ideogRam(), so that I can copy around the inputs files to the accessible locations under htmlwidget folder structure.
```
annotationsPath = "/annotations_tracks_files/Ideogram-0.9.0/data/annotations/1000_virtual_snvs.json",
```

Thanks!
Freeman

**Comment by eweitz** [comment]
> Is there a quick way to pass/assign an id for Ideogram object

Check out the use of [`container`](https://github.com/eweitz/ideogram/blob/master/api.md#container) in the [Multiple, trio](https://eweitz.github.io/ideogram/multiple_trio.html) or [Multiple, primates](https://eweitz.github.io/ideogram/multiple_primates.html) examples.  This property specifies the CSS selector of the HTML element that will contain the ideogram.  

So if you're trying to create multiple ideograms on one page, first create the container elements for each ideogram with your desired IDs, then pass those IDs into each ideogram constructor call via `container` as in those examples.

> Is there a similar solution to dataDir for inputting annotationsPath arg?

Not yet, at least not beyond [loading BED files into an ideogram](http://localhost/ideogram/examples/annotations_file_url.html).  I'm looking into this now.

**Comment by eweitz** [comment]
@wangtulao, I just improved support for specifying `annotationsPath` as a remote URL, e.g.:
```
var config = {
  organism: "human",
  annotationsPath: "https://unpkg.com/ideogram@0.9.0/dist/data/annotations/10_virtual_cnvs.json",
  annotationsLayout: "overlay"
};
var ideogram = new Ideogram(config);
```
You can try this by pulling [ideogram.min.js@0a30fd6](https://github.com/eweitz/ideogram/blob/0a30fd6eddd52d1475f56f067bda8d5d94d369c3/dist/js/ideogram.min.js) into ideogRam.  

Re-reading your question, I'm not confident this will solve your issue, but it's worth a try.  It seems you might want a new config property `annotationsDir`, and for that directory to be inferred like `dataDir`.  This would require changing a few examples and might complicate available `annotations*` properties, but is still worth considering if it turns out you need it.

Let me know how the latest copy of ideogram.min.js works for you, and we'll go from there!

**Comment by wangtulao** [comment]
Thanks a lot @eweitz for pointing me the container solutions. It seems to work! Now I can host multiple ideogram viz in Shiny.
![image](https://user-images.githubusercontent.com/1614226/30309808-3fa109d0-975b-11e7-9cb9-714c363baf53.png)

Also, annotationsPath's new url input feature works well in ideogRam! You are awesome. While considering the case of local usage, I may still figure out another workaround in R, e.g. coping the input files to htmlwidget's relative path, and rebuild the link to under htmlwidget's folder structure. Will try this idea later.

Thanks,
Freeman

**Comment by eweitz** [comment]
> While considering the case of local usage, I may still figure out another workaround in R, e.g. coping the input files to htmlwidget's relative path, and rebuild the link to under htmlwidget's folder structure. Will try this idea later.

@wangtulao, I just released Ideogram.js v0.11.0 with streamlined configuration for your use case (and many other embedding contexts).  You should now be able to omit `dataDir` in your configuration.  

Ideogram.js now fetches data from a public CDN unless A) `dataDir` is explicitly set or B) the embedding web app is hosted on `localhost` or `127.0.0.1` per the browser address bar.

I plan to augment this project's examples to show how to embed Ideogram as a widget in technologies other than plain-old HTML and JavaScript -- e.g. Angular, React, Vue, Jupyter Notebooks.  I'll plan to simply link out to your ideogRam repo for the R / Shiny example.  Thanks again!
